/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Profile;
import javax.swing.JOptionPane;
/**
 *
 * @author Sarthak
 */
public class CreatePanel extends javax.swing.JPanel {
    private Profile profile;
    
    /**
     * Creates new form CreatePanel
     */
    public CreatePanel(Profile profile) {
        initComponents();
        this.profile = profile;
    }

    public CreatePanel() {
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bannerLbl = new javax.swing.JLabel();
        firstNamelbl = new javax.swing.JLabel();
        lastNameLbl = new javax.swing.JLabel();
        middleNameLbl = new javax.swing.JLabel();
        dobLbl = new javax.swing.JLabel();
        addressLbl = new javax.swing.JLabel();
        townLbl = new javax.swing.JLabel();
        zipLbl = new javax.swing.JLabel();
        occupationLbl = new javax.swing.JLabel();
        emailLbl = new javax.swing.JLabel();
        areaCodeLbl = new javax.swing.JLabel();
        phoneNumLbl = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        occupationTextField = new javax.swing.JTextField();
        zipTextField = new javax.swing.JTextField();
        addressTextField = new javax.swing.JTextField();
        dobTextField = new javax.swing.JTextField();
        areaCodeTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        townTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        middleNameTextField = new javax.swing.JTextField();
        phoneNumTextField = new javax.swing.JTextField();
        createBtn = new javax.swing.JButton();

        bannerLbl.setText("Person's Profile");

        firstNamelbl.setText("First name");

        lastNameLbl.setText("Last Name");

        middleNameLbl.setText("Middle Name");

        dobLbl.setText("Date of Birth(YYYY/MM/DD)");

        addressLbl.setText("Street Address");

        townLbl.setText("Town");

        zipLbl.setText("Zip Code");

        occupationLbl.setText("Occupation");

        emailLbl.setText("Email Address");

        areaCodeLbl.setText("Area code of phone number");

        phoneNumLbl.setText("Phone Number");

        lastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextFieldActionPerformed(evt);
            }
        });

        createBtn.setText("Create");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lastNameLbl)
                            .addComponent(middleNameLbl)
                            .addComponent(dobLbl)
                            .addComponent(addressLbl)
                            .addComponent(firstNamelbl)
                            .addComponent(townLbl)
                            .addComponent(zipLbl)
                            .addComponent(occupationLbl)
                            .addComponent(emailLbl)
                            .addComponent(areaCodeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(phoneNumLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(firstNameTextField)
                            .addComponent(areaCodeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(emailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(townTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(occupationTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(zipTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(addressTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(dobTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(lastNameTextField)
                            .addComponent(middleNameTextField)
                            .addComponent(phoneNumTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bannerLbl))))
                .addContainerGap(196, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addressLbl, areaCodeLbl, dobLbl, emailLbl, firstNamelbl, lastNameLbl, middleNameLbl, occupationLbl, phoneNumLbl, townLbl, zipLbl});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(bannerLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNamelbl)
                            .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lastNameLbl))
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(middleNameLbl)
                    .addComponent(middleNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dobLbl)
                    .addComponent(dobTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addressLbl)
                    .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(zipLbl)
                    .addComponent(zipTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(occupationLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(occupationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(townLbl)
                    .addComponent(townTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(areaCodeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(areaCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumLbl)
                    .addComponent(phoneNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(createBtn)
                .addGap(572, 572, 572))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addressLbl, dobLbl, firstNamelbl, lastNameLbl, middleNameLbl});

    }// </editor-fold>//GEN-END:initComponents

    private void lastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextFieldActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        
        profile.setFirstName(firstNameTextField.getText());
        profile.setLastName(lastNameTextField.getText());
        profile.setMiddleName(middleNameTextField.getText());
        profile.setDob(dobTextField.getText());
        profile.setAddress(addressTextField.getText());
        profile.setTown(townTextField.getText());
        profile.setZipCode(zipTextField.getText());
        profile.setOccupation(occupationTextField.getText());
        profile.setEmail(emailTextField.getText());
        profile.setAreaCode(areaCodeTextField.getText());
        profile.setPhoneNum(phoneNumTextField.getText());
        
       
        
        if (firstNameTextField.getText().length()== 0  | lastNameTextField.getText().length()==0 | middleNameTextField.getText().length()==0 | 
                dobTextField.getText().length()==0 | addressTextField.getText().length()==0 | townTextField.getText().length()==0 | 
                zipTextField.getText().length()==0 | occupationTextField.getText().length()==0 | 
                emailTextField.getText().length()==0 | areaCodeTextField.getText().length()==0 | phoneNumTextField.getText().length()==0 
                )
                {
          JOptionPane.showMessageDialog(null, 
                                      "There are Empty fields.\n"
                                              + " Please fill in all the details", 
                                      "Warning", 
                                      JOptionPane.WARNING_MESSAGE );          
                }
                
        else {     
        JOptionPane.showMessageDialog(null, 
                                      "Profile Successfully Created!", 
                                      "Success", 
                                      JOptionPane.INFORMATION_MESSAGE ); }
    }//GEN-LAST:event_createBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLbl;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JLabel areaCodeLbl;
    private javax.swing.JTextField areaCodeTextField;
    private javax.swing.JLabel bannerLbl;
    private javax.swing.JButton createBtn;
    private javax.swing.JLabel dobLbl;
    private javax.swing.JTextField dobTextField;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel firstNamelbl;
    private javax.swing.JLabel lastNameLbl;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel middleNameLbl;
    private javax.swing.JTextField middleNameTextField;
    private javax.swing.JLabel occupationLbl;
    private javax.swing.JTextField occupationTextField;
    private javax.swing.JLabel phoneNumLbl;
    private javax.swing.JTextField phoneNumTextField;
    private javax.swing.JLabel townLbl;
    private javax.swing.JTextField townTextField;
    private javax.swing.JLabel zipLbl;
    private javax.swing.JTextField zipTextField;
    // End of variables declaration//GEN-END:variables
}
