/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.BARole;

import Business.CustomerDirectory;
import Business.MasterOrderCatalog;
import Business.SalespersonDirectory;
import Business.SupplierDirectory;
import java.awt.CardLayout;
import java.util.Collection;
import java.util.Collections;
import javax.swing.JPanel;

/**
 *
 * @author Sarthak
 */
public class BAWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    SalespersonDirectory salespersonDirectory;
    CustomerDirectory customerDirectory;
    MasterOrderCatalog moc;
    SupplierDirectory supplierDirectory;
    
    /**
     * Creates new form BAWorkAreaJPanel
     */
    public BAWorkAreaJPanel(JPanel userProcessContainer, SalespersonDirectory salespersonDirectory, CustomerDirectory customerDirectory,
            MasterOrderCatalog moc, SupplierDirectory supplierDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.salespersonDirectory = salespersonDirectory;
        this.customerDirectory = customerDirectory;
        this.moc = moc;
        this.supplierDirectory = supplierDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        top3btn = new javax.swing.JButton();
        popProdbtn = new javax.swing.JButton();
        aboveTargetPriceBtn = new javax.swing.JButton();
        bestCustomerBtn = new javax.swing.JButton();
        totalCommissionBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        top3btn.setText("Top 3 Salesperson");
        top3btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                top3btnActionPerformed(evt);
            }
        });

        popProdbtn.setText("Most popular product");
        popProdbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popProdbtnActionPerformed(evt);
            }
        });

        aboveTargetPriceBtn.setText("Products sold above target price");
        aboveTargetPriceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboveTargetPriceBtnActionPerformed(evt);
            }
        });

        bestCustomerBtn.setText("Best Customer");
        bestCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bestCustomerBtnActionPerformed(evt);
            }
        });

        totalCommissionBtn.setText("Total Commission per salesperson");
        totalCommissionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalCommissionBtnActionPerformed(evt);
            }
        });

        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalCommissionBtn)
                            .addComponent(bestCustomerBtn)
                            .addComponent(aboveTargetPriceBtn)
                            .addComponent(popProdbtn)
                            .addComponent(top3btn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(backBtn)))
                .addContainerGap(361, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(top3btn)
                .addGap(18, 18, 18)
                .addComponent(popProdbtn)
                .addGap(18, 18, 18)
                .addComponent(aboveTargetPriceBtn)
                .addGap(18, 18, 18)
                .addComponent(bestCustomerBtn)
                .addGap(18, 18, 18)
                .addComponent(totalCommissionBtn)
                .addGap(65, 65, 65)
                .addComponent(backBtn)
                .addContainerGap(211, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void top3btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_top3btnActionPerformed
        Top3Salesperson t3sp = new Top3Salesperson(userProcessContainer, salespersonDirectory, customerDirectory, moc, supplierDirectory);
        userProcessContainer.add("Top3Salesperson", t3sp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_top3btnActionPerformed

    private void popProdbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popProdbtnActionPerformed
        MostPopularProduct mpp = new MostPopularProduct(userProcessContainer, salespersonDirectory, customerDirectory, moc, supplierDirectory);
        userProcessContainer.add("MostPopularProduct", mpp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_popProdbtnActionPerformed

    private void bestCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bestCustomerBtnActionPerformed
        BestCustomer bc = new BestCustomer(userProcessContainer, salespersonDirectory, customerDirectory, moc, supplierDirectory);
        userProcessContainer.add("BestCustomer", bc);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_bestCustomerBtnActionPerformed

    private void totalCommissionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalCommissionBtnActionPerformed
        CommissionPerSalesPerson cpsp = new CommissionPerSalesPerson(userProcessContainer, salespersonDirectory, customerDirectory, moc, supplierDirectory);
        userProcessContainer.add("CommissionPerSalesPerson", cpsp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_totalCommissionBtnActionPerformed

    private void aboveTargetPriceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboveTargetPriceBtnActionPerformed
        TargetPrice atp = new TargetPrice(userProcessContainer, salespersonDirectory, customerDirectory, moc, supplierDirectory);
        userProcessContainer.add("AboveTargetPrice", atp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_aboveTargetPriceBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);        

    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboveTargetPriceBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton bestCustomerBtn;
    private javax.swing.JButton popProdbtn;
    private javax.swing.JButton top3btn;
    private javax.swing.JButton totalCommissionBtn;
    // End of variables declaration//GEN-END:variables
}
