/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Patient;
import Business.Person;
import Business.PersonDirectory;
import Business.VitalSignHistory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sarthak
 */
public class CreatePersonJPanel extends javax.swing.JPanel {

//    private Person person;
    private JPanel userProcessContainer;
    private PersonDirectory personDirectory;
//    private Patient patient;
//    private VitalSignHistory vitalSignHistory;
    /**
     * Creates new form CreatePersonJPanel
     */
    public CreatePersonJPanel(JPanel upc, PersonDirectory personDirectory) {
        initComponents();
        this.userProcessContainer = upc;
        this.personDirectory = personDirectory;
//        this.person = person;
//        this.patient = patient;
//        this.vitalSignHistory = vitalSignHistory;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        banner = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        firstNameTb = new javax.swing.JTextField();
        lastNameTb = new javax.swing.JTextField();
        createBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        personTable = new javax.swing.JTable();
        createPatientBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        idTb = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        banner.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        banner.setText("Please enter Person information:");

        jLabel1.setText("First Name");

        jLabel2.setText("Last Name");

        createBtn.setText("Create Person");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        personTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name"
            }
        ));
        jScrollPane1.setViewportView(personTable);

        createPatientBtn.setText("Create Patient");
        createPatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPatientBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("ID");

        jButton1.setText("View Person");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(74, 74, 74)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(firstNameTb, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(banner)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(144, 144, 144)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lastNameTb)
                                            .addComponent(idTb, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))))
                                .addGap(106, 106, 106))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(createBtn)
                                .addGap(165, 165, 165)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(createPatientBtn)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(39, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(banner)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameTb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameTb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(idTb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createPatientBtn)
                    .addComponent(createBtn)
                    .addComponent(jButton1))
                .addGap(96, 96, 96)
                .addComponent(backBtn)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        String firstName = firstNameTb.getText();
        String lastName = lastNameTb.getText();
        String id = idTb.getText();
        
        Person p = personDirectory.addPerson();
        p.setFirstName(firstName);
        p.setLastName(lastName);
        p.setId(id);
       
        populateTable();
        resetFields();
        
//        CreatepatientJPanel cpajp = new CreatepatientJPanel(userProcessContainer, person, patient, vitalSignHistory);
//        userProcessContainer.add("CreatepatientJPanel", cpajp);
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.next(userProcessContainer);
                
    }//GEN-LAST:event_createBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        WorkAreaJPanel workAreaJPanel = (WorkAreaJPanel) component;
//        workAreaJPanel.refreshTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void createPatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPatientBtnActionPerformed
        
        int selectedRow = personTable.getSelectedRow(); 
        if(selectedRow >=0) {                              
            Person p = (Person) personTable.getValueAt(selectedRow, 0);
            CreatepatientJPanel cpajp = new CreatepatientJPanel(userProcessContainer, p);
            userProcessContainer.add("CreatePatientJPanel", cpajp);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
            
//            RespiratoryTb.setText(String.valueOf(vs.getRespiratoryRate()));
            
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_createPatientBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = personTable.getSelectedRow();
        if(selectedRow >=0) {
            Person p = (Person) personTable.getValueAt(selectedRow, 0);
            ViewPersonJPanel vprjp = new ViewPersonJPanel(userProcessContainer, p);
            userProcessContainer.add("ViewPersonJPanel", vprjp);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

     private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel)personTable.getModel(); 
        int rowCount = personTable.getRowCount();
        for(int i = rowCount - 1; i>=0; i--) {
            dtm.removeRow(i);
        }
        
        for(Person p : personDirectory.getPersonList()) {
            Object row[] = new Object[3];
            row[0] = p;
            row[1] = p.getFirstName();
            row[2] = p.getLastName();
            dtm.addRow(row);
        }
        
    }
     
     
    public void resetFields(){
        firstNameTb.setText("");
        lastNameTb.setText("");
        idTb.setText("");
        
    }

     public void refreshTable() {
        DefaultTableModel dtm = (DefaultTableModel) personTable.getModel();
        dtm.setRowCount(0);
        for (Person p : personDirectory.getPersonList()) {
            Object[] row = new Object[3];
            row[0] = p;
            row[1] = p.getFirstName();
            row[2] = p.getLastName();
            
            dtm.addRow(row);
        }
    }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel banner;
    private javax.swing.JButton createBtn;
    private javax.swing.JButton createPatientBtn;
    private javax.swing.JTextField firstNameTb;
    private javax.swing.JTextField idTb;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameTb;
    private javax.swing.JTable personTable;
    // End of variables declaration//GEN-END:variables
}
