/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Analytics;

import Business.Business;
import Business.Customer;
import Business.Product;
import Business.SalesPerson;
import java.util.Collections;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kedarvdm
 */
public class SalesAnalyticsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SalesAnalyticsJPanel
     */
    private JPanel userProcessContainer;
    private Business business;
    public SalesAnalyticsJPanel(JPanel userProcessContainer, Business business) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.business=business;
        populateSaleCountAnalysis();
        populateTop3SalePersons();
        populateTopSoldProduct();
        populateSalePersonCommissions();
        populateTopCustomer();
    }
    
    private void populateTop3SalePersons()
    {
        Collections.sort(business.getSalesPersonDirectory().getSalesPersonDirectory(), new SalesPerson());
        DefaultTableModel dtm=(DefaultTableModel) top3SalesPersonsJTable.getModel();
        dtm.setRowCount(0);
        int i=0;
        for(SalesPerson sp:business.getSalesPersonDirectory().getSalesPersonDirectory())
        {
            Object row[]=new Object[3];
            row[0]=sp;
            row[1]=sp.getSalesPersonId();
            row[2]=sp.getAboveTarget()+sp.getBelowTarget();
            dtm.addRow(row);
            i++;
            if(i==3)
            {
                break;
            }
        }
    }
    
    private void populateTopSoldProduct()
    {
        Collections.sort(business.getXerox().getProductCatalog().getProductcatalog());
        DefaultTableModel dtm=(DefaultTableModel) topSoldProductJTable.getModel();
        dtm.setRowCount(0);
        int i=0;
        for(Product p:business.getXerox().getProductCatalog().getProductcatalog())
        {
            Object row[]=new Object[2];
            row[0]=p;
            row[1]=p.getSoldCount();
            dtm.addRow(row);
            i++;
            if(i==1)
            {
                break;
            }
        }
    }
    
    private void populateSaleCountAnalysis()
    {
        DefaultTableModel dtm=(DefaultTableModel) saleCountAnalysisJTable.getModel();
        dtm.setRowCount(0);
        for(SalesPerson sp:business.getSalesPersonDirectory().getSalesPersonDirectory())
        {
            Object row[]=new Object[4];
            row[0]=sp;
            row[1]=sp.getSalesPersonId();
            row[2]=sp.getAboveTarget();
            row[3]=sp.getBelowTarget();
            dtm.addRow(row);
        }
    }
    
    private void populateSalePersonCommissions()
    {
        Collections.sort(business.getSalesPersonDirectory().getSalesPersonDirectory());
        DefaultTableModel dtm=(DefaultTableModel) salesPersonCommissionsJTable.getModel();
        dtm.setRowCount(0);
        for(SalesPerson sp:business.getSalesPersonDirectory().getSalesPersonDirectory())
        {
            Object row[]=new Object[3];
            row[0]=sp;
            row[1]=sp.getSalesPersonId();
            row[2]=sp.getTotalCommission();
            dtm.addRow(row);
        }
    }
    
    private void populateTopCustomer()
    {
        Collections.sort(business.getCustomerDirectory().getCustomerDirectory());
        DefaultTableModel dtm=(DefaultTableModel) bestCustomerJTable.getModel();
        dtm.setRowCount(0);
        int i=0;
        for(Customer c:business.getCustomerDirectory().getCustomerDirectory())
        {
            Object row[]=new Object[3];
            row[0]=c;
            row[1]=c.getCustomerID();
            row[2]=c.getBuyCount();
            dtm.addRow(row);
            i++;
            if(i==1)
            {
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        top3SalesPersonsJTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        topSoldProductJTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        saleCountAnalysisJTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        salesPersonCommissionsJTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        bestCustomerJTable = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sales Analytics");

        jLabel2.setText("Top 3 Sales Persons By Sales Volume:");

        top3SalesPersonsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sales Person Name", "ID", "Sales Volume"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(top3SalesPersonsJTable);

        jLabel3.setText("Top Product By Sales Volume:");

        topSoldProductJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Sold Count"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(topSoldProductJTable);

        saleCountAnalysisJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sales Person Name", "ID", "Above Target", "Below Target"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(saleCountAnalysisJTable);

        jLabel4.setText("Sales Person Sale Counts:");

        salesPersonCommissionsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sales Person Name", "ID", "Commission"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(salesPersonCommissionsJTable);

        jLabel5.setText("Commission Paid to each Sales Person:");

        jLabel6.setText("Best Customer:");

        bestCustomerJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Name", "Customer ID", "Sales Volume"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(bestCustomerJTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1))
                        .addComponent(jLabel5))
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane5))
                .addContainerGap(482, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bestCustomerJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable saleCountAnalysisJTable;
    private javax.swing.JTable salesPersonCommissionsJTable;
    private javax.swing.JTable top3SalesPersonsJTable;
    private javax.swing.JTable topSoldProductJTable;
    // End of variables declaration//GEN-END:variables
}
