/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userinterface;
import business.Person;
import javax.swing.JFrame;
/**
 *
 * @author kedarvdm
 */
public class MainJFrame extends javax.swing.JFrame {

    private Person person;
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        this.setVisible(true);
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        this.setTitle("Person Details");
        this.person=new Person();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productSplitPane = new javax.swing.JSplitPane();
        productLeftJPanel = new javax.swing.JPanel();
        createPersonJButton = new javax.swing.JButton();
        viewPersonJButton = new javax.swing.JButton();
        productMenuJLabel = new javax.swing.JLabel();
        productRightJPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 400));

        productSplitPane.setBorder(new javax.swing.border.MatteBorder(null));
        productSplitPane.setDividerLocation(200);
        productSplitPane.setLastDividerLocation(200);
        productSplitPane.setMinimumSize(new java.awt.Dimension(700, 400));
        productSplitPane.setPreferredSize(new java.awt.Dimension(700, 400));

        productLeftJPanel.setBorder(new javax.swing.border.MatteBorder(null));
        productLeftJPanel.setMinimumSize(new java.awt.Dimension(200, 700));
        productLeftJPanel.setNextFocusableComponent(createPersonJButton);
        productLeftJPanel.setPreferredSize(new java.awt.Dimension(200, 700));

        createPersonJButton.setText("Create Person");
        createPersonJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPersonJButtonActionPerformed(evt);
            }
        });

        viewPersonJButton.setText("View Person");
        viewPersonJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPersonJButtonActionPerformed(evt);
            }
        });

        productMenuJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        productMenuJLabel.setText("Person Menu");

        javax.swing.GroupLayout productLeftJPanelLayout = new javax.swing.GroupLayout(productLeftJPanel);
        productLeftJPanel.setLayout(productLeftJPanelLayout);
        productLeftJPanelLayout.setHorizontalGroup(
            productLeftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productLeftJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(productLeftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(createPersonJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewPersonJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productMenuJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        productLeftJPanelLayout.setVerticalGroup(
            productLeftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productLeftJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productMenuJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createPersonJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewPersonJButton)
                .addContainerGap(587, Short.MAX_VALUE))
        );

        productSplitPane.setLeftComponent(productLeftJPanel);

        productRightJPanel.setBorder(new javax.swing.border.MatteBorder(null));
        productRightJPanel.setMinimumSize(new java.awt.Dimension(500, 400));
        productRightJPanel.setPreferredSize(new java.awt.Dimension(500, 400));

        javax.swing.GroupLayout productRightJPanelLayout = new javax.swing.GroupLayout(productRightJPanel);
        productRightJPanel.setLayout(productRightJPanelLayout);
        productRightJPanelLayout.setHorizontalGroup(
            productRightJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );
        productRightJPanelLayout.setVerticalGroup(
            productRightJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 696, Short.MAX_VALUE)
        );

        productSplitPane.setRightComponent(productRightJPanel);

        getContentPane().add(productSplitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createPersonJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPersonJButtonActionPerformed
        // TODO add your handling code here:
        CreatePersonJPanel cpJPanel= new CreatePersonJPanel(person);
        productSplitPane.setRightComponent(cpJPanel);
        
    }//GEN-LAST:event_createPersonJButtonActionPerformed

    private void viewPersonJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPersonJButtonActionPerformed
        // TODO add your handling code here:
        ViewPersonJPanel vpJPanel= new ViewPersonJPanel(person);
        productSplitPane.setRightComponent(vpJPanel);
    }//GEN-LAST:event_viewPersonJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new MainJFrame().setVisible(true);           
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createPersonJButton;
    private javax.swing.JPanel productLeftJPanel;
    private javax.swing.JLabel productMenuJLabel;
    private javax.swing.JPanel productRightJPanel;
    private javax.swing.JSplitPane productSplitPane;
    private javax.swing.JButton viewPersonJButton;
    // End of variables declaration//GEN-END:variables
}
